import 'package:flutter/material.dart';

import 'package:memox/core/theme/tokens/color_tokens.dart';

/// Builds the app `ColorScheme` from a seed.
///
/// Per the design system, the whole scheme is generated by
/// `ColorScheme.fromSeed`. For the default indigo seed the generated roles are
/// then replaced with the curated Tokyo Pure (light) / Tokyo Nebula (dark)
/// tokens from blocks A–C of the token reference. Alternate user-picked seeds
/// use the purely generated scheme (no curated overrides).
abstract final class MxColorScheme {
  MxColorScheme._();

  static const Color defaultSeed = ColorTokens.seedIndigo;

  static ColorScheme light({Color seed = defaultSeed}) {
    final base = ColorScheme.fromSeed(
      seedColor: seed,
      brightness: Brightness.light,
    );
    if (seed != defaultSeed) {
      return base;
    }
    return base.copyWith(
      primary: ColorTokens.primary,
      onPrimary: ColorTokens.onPrimary,
      primaryContainer: ColorTokens.primaryContainer,
      onPrimaryContainer: ColorTokens.onPrimaryContainer,
      secondary: ColorTokens.secondary,
      onSecondary: ColorTokens.onSecondary,
      tertiary: ColorTokens.tertiary,
      onTertiary: ColorTokens.onTertiary,
      error: ColorTokens.error,
      onError: ColorTokens.onError,
      surface: ColorTokens.surface,
      surfaceBright: ColorTokens.surfaceBright,
      surfaceDim: ColorTokens.surfaceDim,
      surfaceContainerLowest: ColorTokens.surfaceContainerLowest,
      surfaceContainerLow: ColorTokens.surfaceContainerLow,
      surfaceContainer: ColorTokens.surfaceContainer,
      surfaceContainerHigh: ColorTokens.surfaceContainerHigh,
      surfaceContainerHighest: ColorTokens.surfaceContainerHighest,
      onSurface: ColorTokens.onSurface,
      onSurfaceVariant: ColorTokens.onSurfaceVariant,
      outline: ColorTokens.outline,
      outlineVariant: ColorTokens.outlineVariant,
    );
  }

  static ColorScheme dark({Color seed = defaultSeed}) {
    final base = ColorScheme.fromSeed(
      seedColor: seed,
      brightness: Brightness.dark,
    );
    if (seed != defaultSeed) {
      return base;
    }
    return base.copyWith(
      primary: ColorTokens.primaryDark,
      onPrimary: ColorTokens.onPrimaryDark,
      primaryContainer: ColorTokens.primaryContainerDark,
      onPrimaryContainer: ColorTokens.onPrimaryContainerDark,
      secondary: ColorTokens.secondaryDark,
      error: ColorTokens.errorDark,
      surface: ColorTokens.surfaceDark,
      surfaceBright: ColorTokens.surfaceBrightDark,
      surfaceDim: ColorTokens.surfaceDimDark,
      surfaceContainerLowest: ColorTokens.surfaceContainerLowestDark,
      surfaceContainerLow: ColorTokens.surfaceContainerLowDark,
      surfaceContainer: ColorTokens.surfaceContainerDark,
      surfaceContainerHigh: ColorTokens.surfaceContainerHighDark,
      surfaceContainerHighest: ColorTokens.surfaceContainerHighestDark,
      onSurface: ColorTokens.onSurfaceDark,
      onSurfaceVariant: ColorTokens.onSurfaceVariantDark,
      outline: ColorTokens.outlineDark,
      outlineVariant: ColorTokens.outlineVariantDark,
    );
  }
}
