import 'package:memox/data/datasources/local/app_database.dart';
import 'package:memox/domain/entities/deck.dart';
import 'package:memox/domain/types/target_language.dart';

/// Maps Drift rows to deck domain types
/// (`docs/contracts/repository-contracts/deck-repository.md`).
abstract final class DeckMapper {
  DeckMapper._();

  static TargetLanguage targetLanguageFromStorage(String value) =>
      switch (value) {
        'english' => TargetLanguage.english,
        'unsupported' => TargetLanguage.unsupported,
        _ => TargetLanguage.korean,
      };

  /// Enum name matches storage form (`korean` / `english` / `unsupported`).
  static String targetLanguageToStorage(TargetLanguage language) =>
      language.name;

  static DateTime _dateFromMs(int ms) =>
      DateTime.fromMillisecondsSinceEpoch(ms, isUtc: true);

  static Deck fromRow(DeckRow row) => fromStorageFields(
    id: row.id,
    folderId: row.folderId,
    name: row.name,
    targetLanguage: row.targetLanguage,
    sortOrder: row.sortOrder,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  );

  /// Converts database storage fields to the domain entity.
  ///
  /// Exact query result classes are generated by Drift and consumed at the
  /// repository boundary instead of being mirrored in this mapper.
  static Deck fromStorageFields({
    required String id,
    required String folderId,
    required String name,
    required String targetLanguage,
    required int sortOrder,
    required int createdAt,
    required int updatedAt,
  }) => Deck(
    id: id,
    folderId: folderId,
    name: name,
    targetLanguage: targetLanguageFromStorage(targetLanguage),
    sortOrder: sortOrder,
    createdAt: _dateFromMs(createdAt),
    updatedAt: _dateFromMs(updatedAt),
  );
}
